from config.settings import INTERFACE_LANGUAGES, RESPONSE_LANGUAGES


PROFILE_LABEL_KEYS = {
    "low": "profile_low",
    "medium": "profile_medium",
    "normal": "profile_normal",
    "high": "profile_high",
    "ultra": "profile_ultra",
    "extreme": "profile_extreme",
    "custom": "profile_custom",
}

HARDWARE_LABEL_KEYS = {
    "cpu": "hardware_cpu",
    "nvidia": "hardware_nvidia",
    "amd": "hardware_amd",
    "intel": "hardware_intel",
}

UI_STRINGS = {
    "en": {
        "app_name": "Desktop AI Assistant",
        "app_subtitle": "Adaptive Local Edition | Glass UI | Smooth Motion | Local GGUF Models",
        "app_send": "Send",
        "app_settings": "Settings",
        "app_copy": "Copy",
        "app_export": "Export",
        "app_clear": "Clear",
        "app_stop": "Stop",
        "app_file": "File",
        "app_image": "Image",
        "app_desktop": "Desktop",
        "app_search": "Search",
        "app_clear_extras": "Clear Extras",
        "app_attach_hint": "Optional tools: attach a text file, add an image, capture the desktop, or include web search results.",
        "app_attached": "Attached extras: {items}",
        "app_attachment_file": 'File "{name}"',
        "app_attachment_image": "{count} image(s)",
        "app_attachment_search": 'Web search "{query}"',
        "app_attachment_memory": "Local memory",
        "app_attachment_python": "Python helper",
        "app_memory_indexed": 'Indexed "{name}" into local memory.',
        "app_memory_index_error": "Local memory indexing failed: {message}",
        "app_placeholder_ready": "Ask anything and press Enter",
        "app_placeholder_loading": "Loading the selected model...",
        "app_placeholder_generating": "Generating a reply...",
        "app_placeholder_lazy": "Ask anything. The model will load when you send your first message.",
        "app_footer": "Enter to send | Esc to hide | {hotkey} to toggle | Ctrl+, for settings | Ctrl+E to export",
        "app_hotkey_unavailable": "hotkey unavailable",
        "app_status_ready": "Ready",
        "app_status_loading": "Loading model",
        "app_status_thinking": "Thinking",
        "app_status_streaming": "Streaming",
        "app_status_stopping": "Stopping",
        "app_status_stopped": "Stopped",
        "app_status_copied": "Copied",
        "app_status_exported": "Exported",
        "app_status_searching": "Searching",
        "app_status_search_attached": "Search attached",
        "app_status_search_error": "Search error",
        "app_status_model_error": "Model error",
        "app_status_reply_error": "Reply error",
        "app_wait_settings": "Wait for the current task to finish before changing settings.",
        "app_chat_cleared": "Chat cleared. Start a new conversation any time.",
        "app_settings_updated": "Settings updated. The conversation has been reset for the new model.",
        "app_generation_stopped": "Generation stopped.",
        "app_generation_error": "Generation error: {message}",
        "app_model_error": "Could not load the selected model: {message}",
        "app_search_error": "Web search failed: {message}",
        "app_search_no_results": "No web results were found for that query.",
        "app_search_attached_message": 'Attached live web search results for "{query}".',
        "app_file_attached": 'Attached file: "{name}"',
        "app_image_attached": 'Attached image: "{name}"',
        "app_desktop_attached": "Desktop screenshot captured. Ask what is on screen or how to use something.",
        "app_desktop_capture_failed": "Desktop capture failed: {message}",
        "app_need_vision_image": "Image attachments require a vision-capable model such as LLaVA 1.5 7B Vision.",
        "app_need_vision_desktop": "Desktop view requires a vision-capable model such as LLaVA 1.5 7B Vision.",
        "app_need_vision_pending": "The current model cannot analyze images. Switch to a vision model or clear the image extras.",
        "app_export_done": "Chat exported to {path}",
        "export_image_attached": "Image attached",
        "app_uploaded": 'Uploaded "{name}"',
        "app_search_context": 'Attached live web search for "{query}"',
        "app_boot_model": "Selected model: {name} ({quantization}, {size} GB).",
        "app_boot_runtime": "{profile} | {hardware} | {language} | {threads}T | CTX {context}",
        "app_boot_vision": "Vision tools are available for screenshots and image uploads.",
        "app_warmup_finished": "Model warmup finished in {seconds:.1f} seconds.",
        "app_model_loaded_sending": "Model loaded in {seconds:.1f} seconds. Sending your question now.",
        "app_ready_message": "Ready. Ask me anything.",
        "app_reply_empty": "The model finished but returned no text. Try a shorter prompt or a different model.",
        "app_reply_failed": "The model could not produce a reply.",
        "app_generation_stopped_inline": "Generation stopped.",
        "caption_you": "YOU",
        "caption_ai": "LOCAL AI",
        "caption_system": "SYSTEM",
        "thinking": "Thinking",
        "setup_title": "Adaptive Setup Wizard",
        "setup_subtitle": "Choose the settings that fit this PC. Once saved, the app will reuse them automatically.",
        "setup_edition_line": "Adaptive Local Edition | Modular setup flow | llama-cpp-python {version}",
        "setup_general": "General Settings",
        "setup_general_desc": "Preset, hardware mode, interface language, assistant reply language, and hotkey.",
        "setup_tuning": "Advanced Tuning",
        "setup_tuning_desc": "Threads, context length, batch size, token limit, history, temperature, and startup options.",
        "setup_models": "Model Library",
        "setup_models_desc": "Choose a model, review compatibility notes, and download the required files.",
        "setup_open": "Open",
        "setup_save": "Save and Continue",
        "setup_cancel": "Cancel",
        "setup_preview": "Runtime Preview",
        "setup_system": "Detected system",
        "setup_selected_model": "Selected model",
        "setup_no_model": "No model selected yet.",
        "setup_ready": "The selected configuration is ready to save.",
        "setup_need_model": "Download the selected model, or place the required GGUF files in the models folder first.",
        "setup_general_title": "General Settings",
        "setup_general_subtitle": "These settings control the overall app experience and default language behavior.",
        "setup_tuning_title": "Advanced Tuning",
        "setup_tuning_subtitle": "These controls affect speed, memory use, and generation length.",
        "setup_model_title": "Model Library",
        "setup_model_subtitle": "Choose a model, review compatibility, and download any missing files.",
        "setup_summary_general": "{profile} | {hardware} | UI {ui_language} | AI {reply_language} | {hotkey}",
        "setup_summary_tuning": "{threads}T | CTX {context} | Batch {batch} | Tokens {tokens}",
        "setup_summary_model": "{name} | {size}",
        "setup_runtime_preview": "{profile} | {hardware} | {language} | {threads}T | CTX {context} | Batch {batch} | Tokens {tokens}",
        "setup_profile_custom_hint": "Saving these values switches the preset to Custom.",
        "setup_ram_warning": "{name} recommends at least {ram} GB RAM for {hardware}.",
        "setup_not_detected": "not detected",
        "setup_field_note": "{label}",
        "field_preset": "Preset",
        "field_hardware": "Hardware mode",
        "field_interface_language": "Interface language",
        "field_reply_language": "Assistant reply language",
        "field_hotkey": "Hotkey",
        "field_threads": "Threads",
        "field_context": "Context length",
        "field_batch": "Batch size",
        "field_max_tokens": "Max output tokens",
        "field_history": "History messages",
        "field_temperature": "Temperature",
        "field_memory_map": "Enable memory mapping",
        "field_warmup": "Warm up model on launch",
        "button_open_models": "Open Models Folder",
        "button_download_model": "Download Selected Model",
        "model_selected_hint": "Selected: {name}. Needs about {size} on disk, recommends at least {ram} GB RAM, and supports: {capabilities}.",
        "setup_download_status": "Downloading {name} into {folder}...",
        "setup_download_done": "Download finished: {name}",
        "setup_download_fail": "Download failed: {message}",
        "setup_download_existing": "{name} is already installed.",
        "download_progress_verified": "Verified existing file: {name}",
        "download_progress_downloading": "Downloading {name}",
        "download_progress_finished": "Finished {name}",
        "system_no_gpu": "No dedicated GPU detected",
        "backend_gpu_fallback": "{hardware} was selected, but the installed llama-cpp-python build does not support GPU offload. Falling back to CPU.",
        "profile_low": "Low",
        "profile_medium": "Medium",
        "profile_normal": "Normal",
        "profile_high": "High",
        "profile_ultra": "Ultra",
        "profile_extreme": "Extreme",
        "profile_custom": "Custom",
        "hardware_cpu": "CPU",
        "hardware_nvidia": "NVIDIA GPU",
        "hardware_amd": "AMD GPU",
        "hardware_intel": "Intel iGPU",
    },
    "zh-TW": {
        "app_name": "桌面 AI 助理",
        "app_subtitle": "自適應本地版 | 玻璃介面 | 流暢動效 | 本地 GGUF 模型",
        "app_send": "送出",
        "app_settings": "設定",
        "app_copy": "複製",
        "app_export": "匯出",
        "app_clear": "清除",
        "app_stop": "停止",
        "app_file": "檔案",
        "app_image": "圖片",
        "app_desktop": "桌面",
        "app_search": "搜尋",
        "app_clear_extras": "清除附件",
        "app_attach_hint": "可選功能：附加文字檔、上傳圖片、擷取桌面畫面，或加入網頁搜尋結果。",
        "app_attached": "已附加：{items}",
        "app_attachment_file": '檔案「{name}」',
        "app_attachment_image": "{count} 張圖片",
        "app_attachment_search": '搜尋「{query}」',
        "app_attachment_memory": "本地記憶",
        "app_attachment_python": "Python 工具",
        "app_memory_indexed": '已將「{name}」索引到本地記憶。',
        "app_memory_index_error": "本地記憶索引失敗：{message}",
        "app_placeholder_ready": "輸入問題後按 Enter 送出",
        "app_placeholder_loading": "正在載入所選模型...",
        "app_placeholder_generating": "正在生成回覆...",
        "app_placeholder_lazy": "直接輸入問題即可，模型會在首次送出時自動載入。",
        "app_footer": "Enter 送出 | Esc 隱藏 | {hotkey} 顯示/隱藏 | Ctrl+, 開啟設定 | Ctrl+E 匯出對話",
        "app_hotkey_unavailable": "快捷鍵無法使用",
        "app_status_ready": "就緒",
        "app_status_loading": "載入模型中",
        "app_status_thinking": "思考中",
        "app_status_streaming": "回覆輸出中",
        "app_status_stopping": "停止中",
        "app_status_stopped": "已停止",
        "app_status_copied": "已複製",
        "app_status_exported": "已匯出",
        "app_status_searching": "搜尋中",
        "app_status_search_attached": "已附加搜尋結果",
        "app_status_search_error": "搜尋失敗",
        "app_status_model_error": "模型錯誤",
        "app_status_reply_error": "回覆錯誤",
        "app_wait_settings": "請先等待目前工作完成，再變更設定。",
        "app_chat_cleared": "對話已清除，隨時都可以開始新的對話。",
        "app_settings_updated": "設定已更新，並已依新模型重設目前對話。",
        "app_generation_stopped": "已停止生成。",
        "app_generation_error": "生成失敗：{message}",
        "app_model_error": "無法載入所選模型：{message}",
        "app_search_error": "網頁搜尋失敗：{message}",
        "app_search_no_results": "找不到符合這個問題的網頁結果。",
        "app_search_attached_message": '已附加「{query}」的網頁搜尋結果。',
        "app_file_attached": '已附加檔案："{name}"',
        "app_image_attached": '已附加圖片："{name}"',
        "app_desktop_attached": "已擷取桌面畫面。你可以直接問畫面上是什麼，或想知道下一步怎麼操作。",
        "app_desktop_capture_failed": "桌面擷取失敗：{message}",
        "app_need_vision_image": "圖片附件需要支援視覺的模型，例如 LLaVA 1.5 7B Vision。",
        "app_need_vision_desktop": "桌面檢視需要支援視覺的模型，例如 LLaVA 1.5 7B Vision。",
        "app_need_vision_pending": "目前模型無法分析圖片。請切換到視覺模型，或先清除圖片附件。",
        "app_export_done": "對話已匯出至 {path}",
        "export_image_attached": "已附加圖片",
        "app_uploaded": '已上傳「{name}」',
        "app_search_context": '已附加「{query}」的即時網頁搜尋',
        "app_boot_model": "目前模型：{name}（{quantization}，{size} GB）。",
        "app_boot_runtime": "{profile} | {hardware} | {language} | {threads} 執行緒 | CTX {context}",
        "app_boot_vision": "目前可使用視覺工具，支援截圖與圖片上傳。",
        "app_warmup_finished": "模型預熱完成，耗時 {seconds:.1f} 秒。",
        "app_model_loaded_sending": "模型已載入完成，耗時 {seconds:.1f} 秒，正在送出你的問題。",
        "app_ready_message": "準備好了，隨時可以開始提問。",
        "app_reply_empty": "模型已結束回覆，但沒有輸出內容。建議改成更短的問題，或切換其他模型再試一次。",
        "app_reply_failed": "模型目前無法產生回覆。",
        "app_generation_stopped_inline": "生成已停止。",
        "caption_you": "你",
        "caption_ai": "本地 AI",
        "caption_system": "系統",
        "thinking": "思考中",
        "setup_title": "自適應設定精靈",
        "setup_subtitle": "依照這台電腦的條件完成設定。儲存後，之後啟動都會自動沿用。",
        "setup_edition_line": "自適應本地版 | 模組化設定流程 | llama-cpp-python {version}",
        "setup_general": "一般設定",
        "setup_general_desc": "設定效能預設、硬體模式、介面語言、AI 回覆語言與快捷鍵。",
        "setup_tuning": "進階微調",
        "setup_tuning_desc": "調整執行緒、上下文長度、批次大小、輸出長度、歷史訊息與啟動行為。",
        "setup_models": "模型庫",
        "setup_models_desc": "選擇要使用的模型、查看相容性說明，並下載缺少的檔案。",
        "setup_open": "開啟",
        "setup_save": "儲存並繼續",
        "setup_cancel": "取消",
        "setup_preview": "執行預覽",
        "setup_system": "偵測到的系統",
        "setup_selected_model": "目前模型",
        "setup_no_model": "尚未選擇模型。",
        "setup_ready": "目前設定可以直接儲存。",
        "setup_need_model": "請先下載所選模型，或將需要的 GGUF 檔案放進 models 資料夾。",
        "setup_general_title": "一般設定",
        "setup_general_subtitle": "這些設定會影響整體使用體驗，以及預設的語言行為。",
        "setup_tuning_title": "進階微調",
        "setup_tuning_subtitle": "這些選項會影響速度、記憶體占用與回覆長度。",
        "setup_model_title": "模型庫",
        "setup_model_subtitle": "選擇模型、查看相容性，並下載缺少的檔案。",
        "setup_summary_general": "{profile} | {hardware} | 介面 {ui_language} | AI {reply_language} | {hotkey}",
        "setup_summary_tuning": "{threads} 執行緒 | CTX {context} | 批次 {batch} | Tokens {tokens}",
        "setup_summary_model": "{name} | {size}",
        "setup_runtime_preview": "{profile} | {hardware} | {language} | {threads} 執行緒 | CTX {context} | 批次 {batch} | Tokens {tokens}",
        "setup_profile_custom_hint": "儲存這些值後，效能預設會自動切換為自訂。",
        "setup_ram_warning": "{name} 建議至少使用 {ram} GB RAM，才適合在 {hardware} 模式下運作。",
        "setup_not_detected": "未偵測到",
        "setup_field_note": "{label}",
        "field_preset": "效能預設",
        "field_hardware": "硬體模式",
        "field_interface_language": "介面語言",
        "field_reply_language": "AI 回覆語言",
        "field_hotkey": "快捷鍵",
        "field_threads": "執行緒數",
        "field_context": "上下文長度",
        "field_batch": "批次大小",
        "field_max_tokens": "最大輸出 Tokens",
        "field_history": "歷史訊息筆數",
        "field_temperature": "溫度",
        "field_memory_map": "啟用記憶體對映",
        "field_warmup": "啟動時預熱模型",
        "button_open_models": "開啟 Models 資料夾",
        "button_download_model": "下載所選模型",
        "model_selected_hint": "目前選擇：{name}。磁碟約需 {size}，建議至少 {ram} GB RAM，支援能力：{capabilities}。",
        "setup_download_status": "正在將 {name} 下載到 {folder}...",
        "setup_download_done": "下載完成：{name}",
        "setup_download_fail": "下載失敗：{message}",
        "setup_download_existing": "{name} 已經安裝完成。",
        "download_progress_verified": "已確認現有檔案：{name}",
        "download_progress_downloading": "正在下載 {name}",
        "download_progress_finished": "已完成 {name}",
        "system_no_gpu": "未偵測到獨立 GPU",
        "backend_gpu_fallback": "你選擇了 {hardware}，但目前安裝的 llama-cpp-python 後端不支援 GPU 卸載，已自動改用 CPU。",
        "profile_low": "低",
        "profile_medium": "中",
        "profile_normal": "標準",
        "profile_high": "高",
        "profile_ultra": "超高",
        "profile_extreme": "極限",
        "profile_custom": "自訂",
        "hardware_cpu": "CPU",
        "hardware_nvidia": "NVIDIA 顯示卡",
        "hardware_amd": "AMD 顯示卡",
        "hardware_intel": "Intel 內顯",
    },
    "zh-CN": {
        "app_name": "桌面 AI 助手",
        "app_subtitle": "自适应本地版 | 玻璃界面 | 流畅动效 | 本地 GGUF 模型",
        "app_send": "发送",
        "app_settings": "设置",
        "app_copy": "复制",
        "app_export": "导出",
        "app_clear": "清空",
        "app_stop": "停止",
        "app_file": "文件",
        "app_image": "图片",
        "app_desktop": "桌面",
        "app_search": "搜索",
        "app_clear_extras": "清除附件",
        "app_attach_hint": "可选功能：附加文本文件、上传图片、截取桌面画面，或加入网页搜索结果。",
        "app_attached": "已附加：{items}",
        "app_attachment_file": '文件“{name}”',
        "app_attachment_image": "{count} 张图片",
        "app_attachment_search": '搜索“{query}”',
        "app_attachment_memory": "本地记忆",
        "app_attachment_python": "Python 工具",
        "app_memory_indexed": '已将“{name}”索引到本地记忆。',
        "app_memory_index_error": "本地记忆索引失败：{message}",
        "app_placeholder_ready": "输入问题后按 Enter 发送",
        "app_placeholder_loading": "正在加载所选模型...",
        "app_placeholder_generating": "正在生成回复...",
        "app_placeholder_lazy": "直接输入问题即可，模型会在首次发送时自动加载。",
        "app_footer": "Enter 发送 | Esc 隐藏 | {hotkey} 显示/隐藏 | Ctrl+, 打开设置 | Ctrl+E 导出对话",
        "app_hotkey_unavailable": "快捷键不可用",
        "app_status_ready": "就绪",
        "app_status_loading": "模型加载中",
        "app_status_thinking": "思考中",
        "app_status_streaming": "回复输出中",
        "app_status_stopping": "停止中",
        "app_status_stopped": "已停止",
        "app_status_copied": "已复制",
        "app_status_exported": "已导出",
        "app_status_searching": "搜索中",
        "app_status_search_attached": "已附加搜索结果",
        "app_status_search_error": "搜索失败",
        "app_status_model_error": "模型错误",
        "app_status_reply_error": "回复错误",
        "app_wait_settings": "请先等待当前任务完成，再修改设置。",
        "app_chat_cleared": "对话已清空，随时都可以开始新的对话。",
        "app_settings_updated": "设置已更新，并已按新模型重置当前对话。",
        "app_generation_stopped": "已停止生成。",
        "app_generation_error": "生成失败：{message}",
        "app_model_error": "无法加载所选模型：{message}",
        "app_search_error": "网页搜索失败：{message}",
        "app_search_no_results": "没有找到符合这个问题的网页结果。",
        "app_search_attached_message": '已附加“{query}”的网页搜索结果。',
        "app_file_attached": '已附加文件：“{name}”',
        "app_image_attached": '已附加图片：“{name}”',
        "app_desktop_attached": "已截取桌面画面。你可以直接问屏幕上是什么，或者下一步该怎么操作。",
        "app_desktop_capture_failed": "桌面截取失败：{message}",
        "app_need_vision_image": "图片附件需要支持视觉的模型，例如 LLaVA 1.5 7B Vision。",
        "app_need_vision_desktop": "桌面查看需要支持视觉的模型，例如 LLaVA 1.5 7B Vision。",
        "app_need_vision_pending": "当前模型无法分析图片。请切换到视觉模型，或先清除图片附件。",
        "app_export_done": "对话已导出到 {path}",
        "export_image_attached": "已附加图片",
        "app_uploaded": '已上传“{name}”',
        "app_search_context": '已附加“{query}”的实时网页搜索',
        "app_boot_model": "当前模型：{name}（{quantization}，{size} GB）。",
        "app_boot_runtime": "{profile} | {hardware} | {language} | {threads} 线程 | CTX {context}",
        "app_boot_vision": "当前可使用视觉工具，支持截图和图片上传。",
        "app_warmup_finished": "模型预热完成，耗时 {seconds:.1f} 秒。",
        "app_model_loaded_sending": "模型已加载完成，耗时 {seconds:.1f} 秒，正在发送你的问题。",
        "app_ready_message": "已经准备好了，随时可以开始提问。",
        "app_reply_empty": "模型已结束回复，但没有输出内容。建议换成更短的问题，或切换其他模型再试一次。",
        "app_reply_failed": "模型当前无法生成回复。",
        "app_generation_stopped_inline": "生成已停止。",
        "caption_you": "你",
        "caption_ai": "本地 AI",
        "caption_system": "系统",
        "thinking": "思考中",
        "setup_title": "自适应设置向导",
        "setup_subtitle": "根据这台电脑的条件完成设置。保存后，后续启动都会自动沿用。",
        "setup_edition_line": "自适应本地版 | 模块化设置流程 | llama-cpp-python {version}",
        "setup_general": "常规设置",
        "setup_general_desc": "设置性能预设、硬件模式、界面语言、AI 回复语言和快捷键。",
        "setup_tuning": "高级调优",
        "setup_tuning_desc": "调整线程数、上下文长度、批大小、输出长度、历史消息和启动行为。",
        "setup_models": "模型库",
        "setup_models_desc": "选择要使用的模型、查看兼容性说明，并下载缺少的文件。",
        "setup_open": "打开",
        "setup_save": "保存并继续",
        "setup_cancel": "取消",
        "setup_preview": "运行预览",
        "setup_system": "检测到的系统",
        "setup_selected_model": "当前模型",
        "setup_no_model": "尚未选择模型。",
        "setup_ready": "当前配置可以直接保存。",
        "setup_need_model": "请先下载所选模型，或将需要的 GGUF 文件放进 models 文件夹。",
        "setup_general_title": "常规设置",
        "setup_general_subtitle": "这些设置会影响整体使用体验，以及默认的语言行为。",
        "setup_tuning_title": "高级调优",
        "setup_tuning_subtitle": "这些选项会影响速度、内存占用和回复长度。",
        "setup_model_title": "模型库",
        "setup_model_subtitle": "选择模型、查看兼容性，并下载缺少的文件。",
        "setup_summary_general": "{profile} | {hardware} | 界面 {ui_language} | AI {reply_language} | {hotkey}",
        "setup_summary_tuning": "{threads} 线程 | CTX {context} | 批大小 {batch} | Tokens {tokens}",
        "setup_summary_model": "{name} | {size}",
        "setup_runtime_preview": "{profile} | {hardware} | {language} | {threads} 线程 | CTX {context} | 批大小 {batch} | Tokens {tokens}",
        "setup_profile_custom_hint": "保存这些数值后，性能预设会自动切换为自定义。",
        "setup_ram_warning": "{name} 建议至少使用 {ram} GB RAM，才适合在 {hardware} 模式下运行。",
        "setup_not_detected": "未检测到",
        "setup_field_note": "{label}",
        "field_preset": "性能预设",
        "field_hardware": "硬件模式",
        "field_interface_language": "界面语言",
        "field_reply_language": "AI 回复语言",
        "field_hotkey": "快捷键",
        "field_threads": "线程数",
        "field_context": "上下文长度",
        "field_batch": "批大小",
        "field_max_tokens": "最大输出 Tokens",
        "field_history": "历史消息条数",
        "field_temperature": "温度",
        "field_memory_map": "启用内存映射",
        "field_warmup": "启动时预热模型",
        "button_open_models": "打开 Models 文件夹",
        "button_download_model": "下载所选模型",
        "model_selected_hint": "当前选择：{name}。磁盘约需 {size}，建议至少 {ram} GB RAM，支持能力：{capabilities}。",
        "setup_download_status": "正在将 {name} 下载到 {folder}...",
        "setup_download_done": "下载完成：{name}",
        "setup_download_fail": "下载失败：{message}",
        "setup_download_existing": "{name} 已经安装完成。",
        "download_progress_verified": "已确认现有文件：{name}",
        "download_progress_downloading": "正在下载 {name}",
        "download_progress_finished": "已完成 {name}",
        "system_no_gpu": "未检测到独立 GPU",
        "backend_gpu_fallback": "你选择了 {hardware}，但当前安装的 llama-cpp-python 后端不支持 GPU 卸载，已自动切换为 CPU。",
        "profile_low": "低",
        "profile_medium": "中",
        "profile_normal": "标准",
        "profile_high": "高",
        "profile_ultra": "超高",
        "profile_extreme": "极限",
        "profile_custom": "自定义",
        "hardware_cpu": "CPU",
        "hardware_nvidia": "NVIDIA 显卡",
        "hardware_amd": "AMD 显卡",
        "hardware_intel": "Intel 核显",
    },
}


LANGUAGE_LABELS = {
    "en": "English",
    "zh-TW": "繁體中文",
    "zh-CN": "简体中文",
    "ja": "日本語",
    "es": "Español",
    "fr": "Français",
    "de": "Deutsch",
    "ko": "한국어",
}

MODEL_COPY = {
    "zh-TW": {
        "tinyllama-1.1b-q4km": {
            "summary": "最輕量的選擇，適合超低規電腦、功能測試與快速介面展示。",
            "recommended_for": "入門級 CPU、8 GB RAM、快速原型和自動化助手。",
            "badge": "最快",
        },
        "gemma-2-2b-q4km": {
            "summary": "小巧的日常助理模型，比超小模型更穩定，負載仍然輕。",
            "recommended_for": "8 GB RAM 的低到中階 CPU 電腦。",
            "badge": "輕巧",
        },
        "qwen-2.5-1.5b-q4km": {
            "summary": "非常小型的現代指令模型，多語言表現比多數超輕量模型更好。",
            "recommended_for": "低到中階 CPU、多語使用者，以及 8 GB RAM 系統。",
            "badge": "小型多語",
        },
        "smollm2-1.7b-q4km": {
            "summary": "體積小、CPU 上很快，整體穩定度又比玩具級模型更好。",
            "recommended_for": "平價桌機、自動化助手，以及想要快速本地 AI 的使用者。",
            "badge": "小型高速",
        },
        "llama-3.2-3b-q4km": {
            "summary": "小尺寸中的均衡款，指令微調較新，品質也比超小模型更好。",
            "recommended_for": "8 到 12 GB RAM 的中階筆電與桌機。",
            "badge": "均衡小型",
        },
        "phi-3.5-mini-q4km": {
            "summary": "推理能力明顯優於超小模型，同時仍保有不錯的 CPU 速度。",
            "recommended_for": "8 到 16 GB RAM 的中階筆電與桌機。",
            "badge": "輕量",
        },
        "mistral-7b-q4km": {
            "summary": "相當常見的指令模型，整體文字品質高，相容性也很廣。",
            "recommended_for": "14 到 16 GB RAM 的桌機 CPU。",
            "badge": "熱門",
        },
        "qwen-2.5-7b-q4km": {
            "summary": "熱門的多語指令模型，長篇回答和多語輸出都比小模型更完整。",
            "recommended_for": "16 GB RAM 的桌機 CPU、多語需求，以及想提升品質又不想上最重模型的使用者。",
            "badge": "熱門多語",
        },
        "llama-3.1-8b-q4km": {
            "summary": "這個專案最推薦的全能型選擇，品質、相容性與 CPU 表現都很均衡。",
            "recommended_for": "Intel Core i7、Ryzen 7 這類現代桌機 CPU，且至少有 16 GB RAM。",
            "badge": "推薦",
        },
        "llava-1.5-7b-q4k": {
            "summary": "可看圖的模型，適合桌面截圖與圖片理解；需要桌面檢視或圖片上傳時就選它。",
            "recommended_for": "16 GB 以上 RAM 的桌機 CPU，以及需要截圖或圖片分析的使用者。",
            "badge": "視覺",
        },
        "mistral-nemo-12b-q4km": {
            "summary": "這份清單中最強的文字模型之一，回答品質更高，但速度更慢、資源需求也更重。",
            "recommended_for": "高階 CPU、24 GB 以上 RAM，以及重視回答品質多於延遲的使用者。",
            "badge": "最強",
        },
    },
    "zh-CN": {
        "tinyllama-1.1b-q4km": {
            "summary": "最轻量的选择，适合超低配电脑、功能测试和快速界面演示。",
            "recommended_for": "入门级 CPU、8 GB RAM、快速原型和自动化助手。",
            "badge": "最快",
        },
        "gemma-2-2b-q4km": {
            "summary": "小巧的日常助手模型，比超小模型更稳定，同时依旧很轻。",
            "recommended_for": "8 GB RAM 的低到中端 CPU 电脑。",
            "badge": "轻巧",
        },
        "qwen-2.5-1.5b-q4km": {
            "summary": "非常小型的现代指令模型，多语言表现比多数超轻量模型更好。",
            "recommended_for": "低到中端 CPU、多语言用户，以及 8 GB RAM 系统。",
            "badge": "小型多语",
        },
        "smollm2-1.7b-q4km": {
            "summary": "体积小、在 CPU 上很快，整体稳定性也比玩具级模型更好。",
            "recommended_for": "入门台式机、自动化助手，以及想要快速本地 AI 的用户。",
            "badge": "小型高速",
        },
        "llama-3.2-3b-q4km": {
            "summary": "小尺寸里的均衡款，指令微调较新，质量也比超小模型更好。",
            "recommended_for": "8 到 12 GB RAM 的中端笔记本和台式机。",
            "badge": "均衡小型",
        },
        "phi-3.5-mini-q4km": {
            "summary": "推理能力明显强于超小模型，同时仍保留不错的 CPU 速度。",
            "recommended_for": "8 到 16 GB RAM 的中端笔记本和台式机。",
            "badge": "轻量",
        },
        "mistral-7b-q4km": {
            "summary": "非常常见的指令模型，整体文字质量高，兼容性也很广。",
            "recommended_for": "14 到 16 GB RAM 的台式机 CPU。",
            "badge": "热门",
        },
        "qwen-2.5-7b-q4km": {
            "summary": "热门的多语言指令模型，长文本回复和多语言输出都比小模型更完整。",
            "recommended_for": "16 GB RAM 的台式机 CPU、多语言需求，以及想提升质量又不想上最重模型的用户。",
            "badge": "热门多语",
        },
        "llama-3.1-8b-q4km": {
            "summary": "这个项目最推荐的全能型选择，质量、兼容性和 CPU 表现都很均衡。",
            "recommended_for": "Intel Core i7、Ryzen 7 这类现代台式机 CPU，并且至少有 16 GB RAM。",
            "badge": "推荐",
        },
        "llava-1.5-7b-q4k": {
            "summary": "支持看图的模型，适合桌面截图和图片理解；需要桌面查看或图片上传时就选它。",
            "recommended_for": "16 GB 以上 RAM 的台式机 CPU，以及需要截图或图片分析的用户。",
            "badge": "视觉",
        },
        "mistral-nemo-12b-q4km": {
            "summary": "这份列表里最强的文本模型之一，回答质量更高，但速度更慢、资源需求也更重。",
            "recommended_for": "高端 CPU、24 GB 以上 RAM，以及更看重回答质量而不是延迟的用户。",
            "badge": "最强",
        },
    },
}


def language_label(language_code: str) -> str:
    return LANGUAGE_LABELS.get(language_code, LANGUAGE_LABELS["en"])


def interface_language_label(language_code: str) -> str:
    return LANGUAGE_LABELS.get(language_code, LANGUAGE_LABELS["en"])


def model_copy(model_id: str, field: str, fallback: str, language_code: str = "en") -> str:
    if language_code == "en":
        return fallback
    return MODEL_COPY.get(language_code, {}).get(model_id, {}).get(field, fallback)


def profile_label(profile_id: str, language_code: str = "en") -> str:
    return tr(PROFILE_LABEL_KEYS.get(profile_id, "profile_custom"), language_code)


def hardware_label(mode_id: str, language_code: str = "en") -> str:
    return tr(HARDWARE_LABEL_KEYS.get(mode_id, "hardware_cpu"), language_code)


def tr(key: str, language_code: str = "en", **kwargs) -> str:
    language_table = UI_STRINGS.get(language_code) or UI_STRINGS["en"]
    template = language_table.get(key, UI_STRINGS["en"].get(key, key))
    return template.format(**kwargs)


def build_system_prompt(language_code: str) -> str:
    preferred_language = language_label(language_code)
    return (
        "You are Desktop AI Assistant, a fast and helpful local AI that runs on the user's computer. "
        "Answer clearly, stay practical, and keep a calm, product-quality tone. "
        f"Always answer in {preferred_language} by default. "
        "Do not switch to another language unless the user explicitly asks for it. "
        "If the user's message is ambiguous, keep using the configured default language. "
        "When files, screenshots, or search results are attached, use them directly and explain what you found in a grounded way."
    )
